import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

const operations = [
  { operationId: "getPublicJobs", method: "GET", path: "/v1/public/jobs" },
  { operationId: "getPublicScams", method: "GET", path: "/v1/public/scams" },
  { operationId: "getPublicReferences", method: "GET", path: "/v1/public/references" },
  { operationId: "getPublicStatus", method: "GET", path: "/v1/public/status" },
  { operationId: "getMeProfile", method: "GET", path: "/v1/me/auth/me" },
  { operationId: "getMeSavedJobs", method: "GET", path: "/v1/me/saved-jobs" },
  { operationId: "getMeNotifications", method: "GET", path: "/v1/me/notifications" },
  { operationId: "getMeBackgroundCheck", method: "GET", path: "/v1/me/background-check" },
  { operationId: "getMePortfolioReviews", method: "GET", path: "/v1/me/portfolio-reviews" },
  { operationId: "getMeSettings", method: "GET", path: "/v1/me/settings" },
  { operationId: "getAdminUsers", method: "GET", path: "/v1/admin/users" },
  { operationId: "getAdminStats", method: "GET", path: "/v1/admin/stats" },
  { operationId: "postInternalIngestJobs", method: "POST", path: "/v1/internal/ingest/jobs" },
  { operationId: "postInternalNotifyDispatch", method: "POST", path: "/v1/internal/notify/dispatch" },
  { operationId: "postInternalChecksLookup", method: "POST", path: "/v1/internal/checks/lookup" },
] as const;

const generatedHeader = `/* eslint-disable */\n// This file is generated by scripts/generate.ts. Do not edit manually.\n`;
const sharedTypes = `\nexport type HttpMethod = "GET" | "POST";\n\nexport type ContractOperation = {\n  readonly operationId: string;\n  readonly method: HttpMethod;\n  readonly path: string;\n};\n\nexport type GeneratedClientRequest = {\n  readonly method: HttpMethod;\n  readonly path: string;\n};\n\n`;

const operationsLiteral = `export const operations = ${JSON.stringify(operations, null, 2)} as const;\n\n`;

const wrappers = operations
  .map(
    (operation) =>
      `export function ${operation.operationId}(): GeneratedClientRequest {\n  return { method: "${operation.method}", path: "${operation.path}" };\n}\n`,
  )
  .join("\n");

const output = `${generatedHeader}${sharedTypes}${operationsLiteral}${wrappers}`;

const outPath = resolve(process.cwd(), "src/generated/client.ts");
writeFileSync(outPath, output, "utf-8");

console.log(`Generated ${operations.length} contract operations at ${outPath}`);
